### ISSUE TITLE
Density of trees

### ISSUE THREAD

**Issue by Ecalpal** [TJU-Aerial-Robotics/YOPO#14]
I noticed that the default value for `avd_tree_staping` in `quadrotor_ros.yaml` is `4.0`, while in your paper you used `density` to represent the average spacing between trees.

So, the `density` is equal to `1/avg_tree_spacing`.

Do I understand this correctly?

**Comment by Lu-tju** [comment]
Hi, density is equal to 1 / avg_tree_spacing^2 (tree/m^2).

**Comment by Ecalpal** [comment]
Thank you for your reply.
