### ISSUE TITLE
The "ctrl cost" in traj_eval_node always outputs "0 m2/s5"

### ISSUE THREAD

**Issue by Ecalpal** [TJU-Aerial-Robotics/YOPO#15]
The traj_eval_node works well before the version on Dec 19th.

**Comment by Lu-tju** [comment]
you can use the `yopo_planner_node` and `test_yopo_ros.py`. In the latest update `test_yopo_ros_new.py`, I remove the unused part to simplify the code, and `traj_eval_node` subscribe the unused topic (which is used in our controller, not the opensource one) for evaluation.

**Comment by Ecalpal** [comment]
Thank you for your reply!
