### ISSUE TITLE
Questions About the camera parameters.

### ISSUE THREAD

**Issue by zhuangzx7** [TJU-Aerial-Robotics/YOPO#4]
Great work! I want to ask why the yaw rotation angle for the left RGB camera in the quadrotor_ros.yaml is -90 degrees. Normally, shouldn't the yaw angle be 0 degrees?

**Comment by Lu-tju** [comment]
You're right, it is weird. It related to the Flightmare Unity, which when set to -90 degrees the camera in the positive direction of `x`
