### ISSUE TITLE
pip install gym==0.21.0  ERROR: python setup.py egg info did not run successfully.

### ISSUE THREAD

**Issue by zxw610** [TJU-Aerial-Robotics/YOPO#5]
when `pip install gym==0.21.0`
problem:
```
error: subprocess-exited-with-error
python setup.py egg_info did not run successfully.
```
solution:
```
pip install setuptools==65.5.0
```

**Comment by zxw610** [comment]
solved

**Comment by Lu-tju** [comment]
You may also need to downgrade the version of pip:
```
pip install pip==24.0
```
if you meet the issue: `please use pip <= 24.1 if ...`

**Comment by ChanJoon** [comment]
The following package versions resolve issues on installation problems with `gym` and `stable-baselines3`, and runtime errors when executing the script:

```bash
pip install --upgrade pip==24.0 wheel==0.38.4 setuptools==65.5.1 protobuf==3.20.3
```
